name: CI - Frontend

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (frontend)
        working-directory: frontend
        run: npm ci

      - name: Run lint (frontend)
        working-directory: frontend
        run: npm run lint --if-present

      - name: Run tests (frontend)
        working-directory: frontend
        run: npm test --silent

      - name: Build (frontend)
        working-directory: frontend
        run: npm run build --if-present

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage
name: CI

on:
  push:
    branches: [ main, v6-alpha ]
  pull_request:
    branches: [ main, v6-alpha ]

jobs:
  build:
    name: Build, Lint, Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Run tests (with coverage)
        run: npm run test -- --coverage --ci

      - name: Build
        run: npm run build

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: coverage
