name: Commit & Deploy (manual)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to push to'
        required: false
        default: 'main'

jobs:
  commit-and-deploy:
    name: Commit changes, Push, and Deploy to Vercel
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit generated files (if any)
        id: commit
        run: |
          BRANCH=${{ github.event.inputs.branch || 'main' }}
          echo "Target branch: $BRANCH"
          git add docs || true
          git add frontend || true
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: update generated docs / build [skip ci]" || true
            git push origin HEAD:$BRANCH
            echo "committed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "committed=false" >> $GITHUB_OUTPUT
          fi

      - name: Install frontend deps
        if: always()
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build --if-present

      - name: Deploy to Vercel
        if: always()
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
